### PR TITLE
Updated the Dockerfile to use a hard-coded artifact version to allow …

### PR DESCRIPTION
**Pull request by zmoore-usgs**
…us to keep java artifact and docker file versions linked.

### CODE REVIEW

**Comment by isuftin** [comment]
This looks good - remember that when you go to 0.0.1 release in the Java project, you will want to update the Dockerfile with that version and tag this repo @ 0.0.1 before cutting a new image

**Comment by isuftin** [comment]
Though I'm not sure why you changed ARG to ENV? Will that work when building the image?

**Comment by isuftin** [comment]
Looked it up. Looks like ENV can also be used at build time. But ARG is not cached into the image. ENV is.

**Comment by isuftin** [comment]
Note: https://docs.docker.com/engine/reference/builder/#impact-on-build-caching

**Comment by isuftin** [comment]
Also note that this will require a change in the Jenkins job that builds this image since you no longer make use of the `--build-args` flag

**Comment by zmoore-usgs** [comment]
@isuftin Yeah @kmschoep-usgs has been working on the changes to the job. I went with ENV because Dave and I were looking at how other docker files (we looked at openjdk-alpine) were including their version numbers for artifacts and they were using ENV. Not sure if it matters much one way or the other? I don't think the ENV names being used should override anything being used by the application in the environment.

**Pull request merged**
